name: Fineract_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

resources:
  pipelines:
   - pipeline: fineract-CD
     source: fineract-CI
     trigger:
      branches:
       include:
         - master
         - develop
         - pull/*
         - refs/pull/*

pool:
  vmImage: ubuntu-latest

variables:
  AzureSubscription: 'Azure Service Connection'
  ClusterResourceGroup: MSF-AKS-Nao-Produtivo-RG
  AksClusterName: msf-aks
  HelmVersion: 3.5.0
  ChartPackage: '$(Pipeline.Workspace)/fineract/fineract-$(resources.pipeline.CustomerApiBuild.runname).tgz' 
  ReleaseValuesFile: '$(Pipeline.Workspace)/fineract/values.release.yaml' 
  ApiName: 'fineract'

stages:
- stage: Dev     
  # condition: startsWith(variables['resources.pipeline.CustomerApiBuild.sourcebranch'], 'refs/heads/master')
  variables:
    DeploymentEnvironment: 'dev'
    K8sNamespace: '$(ApiName)-$(DeploymentEnvironment)'
    URL: $(DeploymentEnvironment).$(SubDomain)
  jobs:
  - deployment: Web_Test
    displayName: 'Deploy CustomerApi to the customerapi-test environment'
    environment: customerapi-test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: CustomerApiBuild
            artifact: $(ArtifactName)
          - template: templates/DeployHelmPackage.yml
            parameters:
              azureSubscription: '$(AzureSubscription)'
              clusterResourceGroup: '$(ClusterResourceGroup)'
              kubernetesCluster: $(AksClusterName)
              helmVersion: $(HelmVersion)
              k8sNamespace: $(K8sNamespace)
              chartPackage: '$(ChartPackage)'              
              releaseValuesFile: '$(ReleaseValuesFile)' 
              apiName: $(ApiName)