{{- if .Values.ingress.enabled -}}
{{- $fullName := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /fineract-provider
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-backend
                port: 
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-ui
                port: 
                  number: 80
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end -}}
